// API 类型定义（内联，不依赖 openapi-typescript 生成结果）
// Generated by: manually maintained

export interface LoginRequest {
  username: string
  password: string
}

export interface LoginResponse {
  token: string
  user: {
    id: number
    username: string
    nickname: string
    email?: string
    role: string
    tenant_id?: number
    status?: number
    /** 首登/被重置后必须改密 */
    mustChangePassword?: boolean
    created_at?: string
    updated_at?: string
  }
}

export interface UserInfo {
  id: number
  username: string
  nickname: string
  email?: string
  role: string
  status: string
  created_at?: string
}

export interface RegisterRequest {
  username: string
  password: string
  nickname?: string
}

// ── 通用值 / 表单 / 日志类型（替代散落的 Record<string, any>） ──

/** 实体 / 表单字段的合法值（替代 `any`，保留类型安全）
 * 含 `string[]`：多选字段（如角色 role）在表单态中本就存数组 */
export type FormValue = string | number | boolean | null | string[]

/** 动态实体表单状态（EntityPage / $table / department / job 等） */
export type EntityFormValues = Record<string, FormValue>

/** 监控日志等通用表行 */
export type LogRow = Record<string, FormValue>

/** 列表响应信封（与 client.apiList 对齐） */
export interface ApiListResult<T> {
  data: T[]
  total: number
  page: number
  pageSize: number
}
