/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MRouteImport } from './routes/m'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SiteRouteImport } from './routes/site'
import { Route as AiApprovalsRouteImport } from './routes/ai/approvals'
import { Route as AiAssistantRouteImport } from './routes/ai/assistant'
import { Route as AiTasksRouteImport } from './routes/ai/tasks'
import { Route as AutomationIntegrationsRouteImport } from './routes/automation/integrations'
import { Route as AutomationWorkflowsRouteImport } from './routes/automation/workflows'
import { Route as BusinessCustomersRouteImport } from './routes/business/customers'
import { Route as BusinessFormsRouteImport } from './routes/business/forms'
import { Route as BusinessLeadsRouteImport } from './routes/business/leads'
import { Route as ContentArticlesRouteImport } from './routes/content/articles'
import { Route as ContentMediaRouteImport } from './routes/content/media'
import { Route as ContentPagesRouteImport } from './routes/content/pages'
import { Route as ContentProductsRouteImport } from './routes/content/products'
import { Route as ContentTagsRouteImport } from './routes/content/tags'
import { Route as FFormIdRouteImport } from './routes/f.$formId'
import { Route as TeamRolesRouteImport } from './routes/team/roles'
import { Route as TeamUsersRouteImport } from './routes/team/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AiApprovalsRoute = AiApprovalsRouteImport.update({
  id: '/ai/approvals',
  path: '/ai/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai/assistant',
  path: '/ai/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTasksRoute = AiTasksRouteImport.update({
  id: '/ai/tasks',
  path: '/ai/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIntegrationsRoute = AutomationIntegrationsRouteImport.update({
  id: '/automation/integrations',
  path: '/automation/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationWorkflowsRoute = AutomationWorkflowsRouteImport.update({
  id: '/automation/workflows',
  path: '/automation/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCustomersRoute = BusinessCustomersRouteImport.update({
  id: '/business/customers',
  path: '/business/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessFormsRoute = BusinessFormsRouteImport.update({
  id: '/business/forms',
  path: '/business/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLeadsRoute = BusinessLeadsRouteImport.update({
  id: '/business/leads',
  path: '/business/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentArticlesRoute = ContentArticlesRouteImport.update({
  id: '/content/articles',
  path: '/content/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMediaRoute = ContentMediaRouteImport.update({
  id: '/content/media',
  path: '/content/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentPagesRoute = ContentPagesRouteImport.update({
  id: '/content/pages',
  path: '/content/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentProductsRoute = ContentProductsRouteImport.update({
  id: '/content/products',
  path: '/content/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTagsRoute = ContentTagsRouteImport.update({
  id: '/content/tags',
  path: '/content/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const FFormIdRoute = FFormIdRouteImport.update({
  id: '/f/$formId',
  path: '/f/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRolesRoute = TeamRolesRouteImport.update({
  id: '/team/roles',
  path: '/team/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamUsersRoute = TeamUsersRouteImport.update({
  id: '/team/users',
  path: '/team/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/m': typeof MRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/site': typeof SiteRoute
  '/ai/approvals': typeof AiApprovalsRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/tasks': typeof AiTasksRoute
  '/automation/integrations': typeof AutomationIntegrationsRoute
  '/automation/workflows': typeof AutomationWorkflowsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/forms': typeof BusinessFormsRoute
  '/business/leads': typeof BusinessLeadsRoute
  '/content/articles': typeof ContentArticlesRoute
  '/content/media': typeof ContentMediaRoute
  '/content/pages': typeof ContentPagesRoute
  '/content/products': typeof ContentProductsRoute
  '/content/tags': typeof ContentTagsRoute
  '/f/$formId': typeof FFormIdRoute
  '/team/roles': typeof TeamRolesRoute
  '/team/users': typeof TeamUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/m': typeof MRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/site': typeof SiteRoute
  '/ai/approvals': typeof AiApprovalsRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/tasks': typeof AiTasksRoute
  '/automation/integrations': typeof AutomationIntegrationsRoute
  '/automation/workflows': typeof AutomationWorkflowsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/forms': typeof BusinessFormsRoute
  '/business/leads': typeof BusinessLeadsRoute
  '/content/articles': typeof ContentArticlesRoute
  '/content/media': typeof ContentMediaRoute
  '/content/pages': typeof ContentPagesRoute
  '/content/products': typeof ContentProductsRoute
  '/content/tags': typeof ContentTagsRoute
  '/f/$formId': typeof FFormIdRoute
  '/team/roles': typeof TeamRolesRoute
  '/team/users': typeof TeamUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/m': typeof MRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/site': typeof SiteRoute
  '/ai/approvals': typeof AiApprovalsRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/tasks': typeof AiTasksRoute
  '/automation/integrations': typeof AutomationIntegrationsRoute
  '/automation/workflows': typeof AutomationWorkflowsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/forms': typeof BusinessFormsRoute
  '/business/leads': typeof BusinessLeadsRoute
  '/content/articles': typeof ContentArticlesRoute
  '/content/media': typeof ContentMediaRoute
  '/content/pages': typeof ContentPagesRoute
  '/content/products': typeof ContentProductsRoute
  '/content/tags': typeof ContentTagsRoute
  '/f/$formId': typeof FFormIdRoute
  '/team/roles': typeof TeamRolesRoute
  '/team/users': typeof TeamUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/home'
    | '/login'
    | '/m'
    | '/profile'
    | '/register'
    | '/settings'
    | '/site'
    | '/ai/approvals'
    | '/ai/assistant'
    | '/ai/tasks'
    | '/automation/integrations'
    | '/automation/workflows'
    | '/business/customers'
    | '/business/forms'
    | '/business/leads'
    | '/content/articles'
    | '/content/media'
    | '/content/pages'
    | '/content/products'
    | '/content/tags'
    | '/f/$formId'
    | '/team/roles'
    | '/team/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/home'
    | '/login'
    | '/m'
    | '/profile'
    | '/register'
    | '/settings'
    | '/site'
    | '/ai/approvals'
    | '/ai/assistant'
    | '/ai/tasks'
    | '/automation/integrations'
    | '/automation/workflows'
    | '/business/customers'
    | '/business/forms'
    | '/business/leads'
    | '/content/articles'
    | '/content/media'
    | '/content/pages'
    | '/content/products'
    | '/content/tags'
    | '/f/$formId'
    | '/team/roles'
    | '/team/users'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/home'
    | '/login'
    | '/m'
    | '/profile'
    | '/register'
    | '/settings'
    | '/site'
    | '/ai/approvals'
    | '/ai/assistant'
    | '/ai/tasks'
    | '/automation/integrations'
    | '/automation/workflows'
    | '/business/customers'
    | '/business/forms'
    | '/business/leads'
    | '/content/articles'
    | '/content/media'
    | '/content/pages'
    | '/content/products'
    | '/content/tags'
    | '/f/$formId'
    | '/team/roles'
    | '/team/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MRoute: typeof MRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SiteRoute: typeof SiteRoute
  AiApprovalsRoute: typeof AiApprovalsRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AiTasksRoute: typeof AiTasksRoute
  AutomationIntegrationsRoute: typeof AutomationIntegrationsRoute
  AutomationWorkflowsRoute: typeof AutomationWorkflowsRoute
  BusinessCustomersRoute: typeof BusinessCustomersRoute
  BusinessFormsRoute: typeof BusinessFormsRoute
  BusinessLeadsRoute: typeof BusinessLeadsRoute
  ContentArticlesRoute: typeof ContentArticlesRoute
  ContentMediaRoute: typeof ContentMediaRoute
  ContentPagesRoute: typeof ContentPagesRoute
  ContentProductsRoute: typeof ContentProductsRoute
  ContentTagsRoute: typeof ContentTagsRoute
  FFormIdRoute: typeof FFormIdRoute
  TeamRolesRoute: typeof TeamRolesRoute
  TeamUsersRoute: typeof TeamUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/approvals': {
      id: '/ai/approvals'
      path: '/ai/approvals'
      fullPath: '/ai/approvals'
      preLoaderRoute: typeof AiApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/assistant': {
      id: '/ai/assistant'
      path: '/ai/assistant'
      fullPath: '/ai/assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/tasks': {
      id: '/ai/tasks'
      path: '/ai/tasks'
      fullPath: '/ai/tasks'
      preLoaderRoute: typeof AiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/integrations': {
      id: '/automation/integrations'
      path: '/automation/integrations'
      fullPath: '/automation/integrations'
      preLoaderRoute: typeof AutomationIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/workflows': {
      id: '/automation/workflows'
      path: '/automation/workflows'
      fullPath: '/automation/workflows'
      preLoaderRoute: typeof AutomationWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/customers': {
      id: '/business/customers'
      path: '/business/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof BusinessCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/forms': {
      id: '/business/forms'
      path: '/business/forms'
      fullPath: '/business/forms'
      preLoaderRoute: typeof BusinessFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/leads': {
      id: '/business/leads'
      path: '/business/leads'
      fullPath: '/business/leads'
      preLoaderRoute: typeof BusinessLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/articles': {
      id: '/content/articles'
      path: '/content/articles'
      fullPath: '/content/articles'
      preLoaderRoute: typeof ContentArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/media': {
      id: '/content/media'
      path: '/content/media'
      fullPath: '/content/media'
      preLoaderRoute: typeof ContentMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/pages': {
      id: '/content/pages'
      path: '/content/pages'
      fullPath: '/content/pages'
      preLoaderRoute: typeof ContentPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/products': {
      id: '/content/products'
      path: '/content/products'
      fullPath: '/content/products'
      preLoaderRoute: typeof ContentProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/tags': {
      id: '/content/tags'
      path: '/content/tags'
      fullPath: '/content/tags'
      preLoaderRoute: typeof ContentTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$formId': {
      id: '/f/$formId'
      path: '/f/$formId'
      fullPath: '/f/$formId'
      preLoaderRoute: typeof FFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/roles': {
      id: '/team/roles'
      path: '/team/roles'
      fullPath: '/team/roles'
      preLoaderRoute: typeof TeamRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/users': {
      id: '/team/users'
      path: '/team/users'
      fullPath: '/team/users'
      preLoaderRoute: typeof TeamUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MRoute: MRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SiteRoute: SiteRoute,
  AiApprovalsRoute: AiApprovalsRoute,
  AiAssistantRoute: AiAssistantRoute,
  AiTasksRoute: AiTasksRoute,
  AutomationIntegrationsRoute: AutomationIntegrationsRoute,
  AutomationWorkflowsRoute: AutomationWorkflowsRoute,
  BusinessCustomersRoute: BusinessCustomersRoute,
  BusinessFormsRoute: BusinessFormsRoute,
  BusinessLeadsRoute: BusinessLeadsRoute,
  ContentArticlesRoute: ContentArticlesRoute,
  ContentMediaRoute: ContentMediaRoute,
  ContentPagesRoute: ContentPagesRoute,
  ContentProductsRoute: ContentProductsRoute,
  ContentTagsRoute: ContentTagsRoute,
  FFormIdRoute: FFormIdRoute,
  TeamRolesRoute: TeamRolesRoute,
  TeamUsersRoute: TeamUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
